// 启动全新的 fixture_core.py 后，用 Playwright browser_run_code_unsafe 的 filename 参数运行。
async (page) => {
  const checks = [];
  const verify = (condition, label) => { if (!condition) throw new Error(label); checks.push(label); };
  const ready = async name => {
    await page.waitForFunction(value => document.querySelector('#project-name').textContent === value, name);
    await page.locator('#connection-status[data-state="connected"]').waitFor();
  };
  const menu = async name => {
    await page.getByRole('button', { name: `管理项目 ${name}`, exact: true }).click();
    await page.locator('.project-remove-action').click();
  };
  await page.goto('http://127.0.0.1:7440/?desktop=1');
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.locator('#connection-status[data-state="connected"]').waitFor();
  await page.waitForFunction(() => document.querySelectorAll('.sidebar-project-row').length === 3);
  const original = await page.locator('#project-name').innerText();
  const alternate = 'another-project';
  await page.locator('#project-button').click();
  await page.locator('.project-option').first().waitFor();
  const bounds = await page.locator('#project-popover').boundingBox();
  const anchor = await page.locator('#project-button').boundingBox();
  verify(bounds.width <= 336 && bounds.height < 400 && bounds.y + bounds.height <= anchor.y, '选择器紧贴项目按钮向上展开，尺寸紧凑');
  verify(!await page.locator('#modal').evaluate(el => el.open), '切换项目不打开模态遮罩');
  await page.getByRole('searchbox', { name: '搜索工作区' }).fill('another');
  verify(await page.locator('.project-option').count() === 1, '项目按名称搜索');
  await page.keyboard.press('ArrowDown');
  verify(await page.locator('.project-option').evaluate(el => el === document.activeElement), '方向键进入项目选项');
  await page.keyboard.press('Escape');
  verify(await page.locator('#project-popover').isHidden() && await page.locator('#project-button').evaluate(el => el === document.activeElement), 'Escape 关闭并恢复触发按钮焦点');
  await page.locator('#project-button').click();
  await page.locator('.project-option').first().waitFor();
  await page.locator('#prompt').click();
  verify(await page.locator('#project-popover').isHidden(), '点击输入框直接收起浮层');
  await page.locator('.project-nav-item').filter({ hasText: alternate }).click();
  await ready(alternate);
  verify(await page.locator('.sidebar-project-row.selected').innerText() === alternate, '侧栏点击切换实际项目');
  await page.locator('#prompt').fill('移除其他项目时保留的草稿');
  await menu(original);
  await page.waitForFunction(() => document.querySelectorAll('.sidebar-project-row').length === 2);
  verify(await page.locator('#project-name').innerText() === alternate && await page.locator('#prompt').inputValue() === '移除其他项目时保留的草稿', '移除非当前项目保留工作区与草稿');
  await page.getByRole('button', { name: '打开项目文件夹', exact: true }).click();
  await ready(original);
  await page.locator('#project-button').click();
  await page.getByRole('button', { name: `从列表移除 ${original}`, exact: true }).click();
  await ready('默认工作区');
  await page.locator('.project-nav-item').filter({ hasText: alternate }).click();
  await ready(alternate);
  verify(await page.locator('#prompt').inputValue() === '移除其他项目时保留的草稿', '回到其他项目后恢复其草稿');
  await page.locator('#prompt').fill('');
  await menu(alternate);
  await ready('默认工作区');
  verify(await page.locator('.sidebar-project-row').count() === 1 && await page.locator('#prompt').isEnabled() && await page.locator('#attach-button').isEnabled(), '移除最后一个项目后默认工作区仍可聊天和添加附件');
  await page.reload();
  await ready('默认工作区');
  verify(await page.locator('#prompt').isEnabled(), '重新载入保持可用的默认工作区');
  await page.getByRole('button', { name: '打开项目文件夹', exact: true }).click();
  await ready(original);
  verify(await page.locator('#prompt').isEnabled(), '重新添加原文件夹恢复可用工作区');
  await page.locator('#prompt').fill('项目移除运行保护测试');
  await page.getByRole('button', { name: '发送消息', exact: true }).click();
  await page.getByRole('button', { name: '允许一次', exact: true }).waitFor();
  await menu(original);
  await page.locator('.project-action-error:not([hidden])').waitFor();
  verify((await page.locator('.project-action-error').innerText()).includes('正在运行') && await page.locator('.sidebar-project-row').count() === 2, '运行中的项目拒绝移除且就地显示原因');
  await page.getByRole('button', { name: '停止当前任务', exact: true }).click();
  await page.getByRole('button', { name: '发送消息', exact: true }).waitFor();
  return { passed: checks.length, checks };
}
