// 启动 fixture_core.py 后，通过 Playwright browser_run_code_unsafe 的 filename 参数运行。
async (page) => {
  const checks = [];
  const verify = (condition, label) => { if (!condition) throw new Error(label); checks.push(label); };
  await page.goto('http://127.0.0.1:7440/?desktop=1');
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.locator('#connection-status[data-state="connected"]').waitFor();
  await page.locator('#new-chat').click();
  await page.locator('#model-button').click();
  await page.getByLabel('Fixture Fast', { exact: false }).check();
  await page.getByRole('button', { name: '使用此模型', exact: true }).click();
  verify(await page.locator('#model-name').innerText() === 'fixture-fast', '模型选择应用到会话');
  await page.locator('#permission-mode').click();
  await page.getByRole('radio', { name: '只读', exact: false }).check();
  await page.getByRole('button', { name: '应用设置', exact: true }).click();
  verify(await page.locator('#permission-mode').innerText() === '只读', '权限设置可操作');
  await page.locator('#permission-mode').click();
  await page.getByRole('radio', { name: '按需审批', exact: false }).check();
  await page.getByRole('button', { name: '应用设置', exact: true }).click();
  await page.evaluate(() => {
    const transfer = new DataTransfer();
    transfer.items.add(new File(['print("actual attachment contents")'], 'example.py', { type: 'text/plain' }));
    const input = document.querySelector('#file-picker');
    input.files = transfer.files;
    input.dispatchEvent(new Event('change', { bubbles: true }));
  });
  await page.locator('.attachment-chip').waitFor();
  await page.locator('#prompt').fill('E2E 检查文件');
  await page.getByRole('button', { name: '发送消息', exact: true }).click();
  await page.getByRole('button', { name: '允许一次', exact: true }).waitFor();
  await page.getByRole('button', { name: '允许一次', exact: true }).click();
  await page.getByRole('button', { name: '发送消息', exact: true }).waitFor();
  verify((await page.locator('#messages').innerText()).includes('README 已检查'), '附件聊天与工具审批完成');
  await page.locator('#conversation-menu').click();
  await page.getByLabel('对话名称', { exact: true }).fill('E2E 桌面交互');
  await page.getByRole('button', { name: '保存名称', exact: true }).click();
  await page.reload();
  await page.locator('#connection-status[data-state="connected"]').waitFor();
  await page.locator('#messages').getByText('actual attachment contents', { exact: false }).waitFor();
  verify(await page.locator('#conversation-title').innerText() === 'E2E 桌面交互', '重命名及服务端历史恢复');
  await page.locator('#prompt').fill('继续，然后停止');
  await page.getByRole('button', { name: '发送消息', exact: true }).click();
  await page.getByRole('button', { name: '允许一次', exact: true }).waitFor();
  await page.reload();
  await page.locator('#connection-status[data-state="connected"]').waitFor();
  await page.getByRole('button', { name: '允许一次', exact: true }).waitFor();
  checks.push('断线重载后恢复待审批卡片');
  await page.getByRole('button', { name: '停止当前任务', exact: true }).click();
  await page.getByRole('button', { name: '发送消息', exact: true }).waitFor();
  verify((await page.locator('#messages').innerText()).includes('已停止本次任务'), '停止等待审批的运行');
  await page.getByRole('button', { name: '已安排', exact: true }).click();
  await page.getByRole('button', { name: '新建任务', exact: true }).click();
  const title = 'E2E 定时任务 ' + Date.now();
  await page.getByLabel('任务名称').fill(title);
  await page.getByLabel('让 MiniClaude 做什么').fill('检查测试项目');
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  await page.locator('#modal').waitFor({ state: 'hidden' });
  const job = page.locator('.management-row').filter({ hasText: title });
  await job.getByRole('button', { name: '立即运行', exact: true }).click();
  await job.getByRole('button', { name: '查看运行', exact: true }).click();
  await page.getByRole('button', { name: '允许一次', exact: true }).waitFor();
  await page.getByRole('button', { name: '拒绝', exact: true }).click();
  await page.getByRole('button', { name: '发送消息', exact: true }).waitFor();
  verify((await page.locator('#messages').innerText()).includes('已跳过被拒绝'), '计划立即运行可打开会话并审批');
  await page.getByRole('button', { name: '已安排', exact: true }).click();
  await job.getByText('已完成', { exact: false }).waitFor();
  await job.getByRole('button', { name: '删除 ' + title, exact: true }).click();
  await page.getByRole('button', { name: '删除任务', exact: true }).click();
  await job.waitFor({ state: 'detached' });
  checks.push('计划结果事件和删除');
  await page.getByRole('button', { name: '插件', exact: true }).click();
  await page.getByRole('button', { name: '添加 MCP 服务', exact: true }).click();
  await page.getByLabel('连接方式').selectOption('tcp');
  verify(await page.getByLabel('主机', { exact: true }).isVisible(), '插件管理有结构化连接表单');
  await page.getByRole('button', { name: '关闭对话框', exact: true }).click();
  await page.getByRole('button', { name: 'Pull Request', exact: true }).click();
  await page.getByRole('heading', { name: '连接这个项目的 Pull Request', exact: true }).waitFor();
  checks.push('PR 页面显示真实仓库连接状态');
  await page.locator('#new-chat').click();
  await page.setViewportSize({ width: 900, height: 650 });
  verify(await page.locator('#send-button').isVisible(), '最小桌面尺寸可操作');
  await page.setViewportSize({ width: 1440, height: 960 });
  return checks;
}
